{
    "name": "AliceVolume",
    "speakableName": "adjust audio volume",
    "version": "1.0.1",
    "icon": "fab fa-battle-net",
    "category": "assistance",
    "author": "lazza",
    "maintainers": [],
    "desc": "Control the volume of Alice",
    "aliceMinVersion": "1.0.0-b3",
    "pipRequirements": [],
    "systemRequirements": [],
    "conditions": {
        "lang": [
            "en"
        ],
        "asrArbitraryCapture": true
    }
}
